# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0159aaa96e877372bd3d85eb78de565877c222ecbf84a92d8f29e49d4f93596a53b9a8860049047feff9aa8dda9a13172a53e64dc741864795ae34e1ebe7846

test:
  secret_key_base: bdaf3222ed6c9adac32f289df2f90ed4a155787ae722f3b8225c25fcc92d49f808f0fc3ac2d057c0611554ce57390a9d74a8d2ea000b5aa8a0a75b0c65480d07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
